### ISSUE TITLE
Remove Project Specific Code and Documentation

### ISSUE THREAD

**Issue by joneubank** [CancerCollaboratory/storage#419]
## Background
Score was originally written as software dedicated to the ICGC 25k project, and later was customized with custom implementation code for use with KidsFirst DRC. Although it has since been integrated in to the Overture DMS ecosystem, there are many vestiges of these older implementations remaining in the code base. These lingering references take many forms, from trivial code comments and naming confusion in documentation, through to dedicate packages with dedicated implementations of Score components.

At this time, it is perfectly fine to use Score as a generic product and integrate it into new projects, but the remaining project specific references in the code base can confuse Score users with:
- error messages that reference specific projects
- default configurations referencing specific environments (most of which no longer exist)
- profile names, sometimes required, that are named for specific projects and environments

### Projects Referenced
- **ICGC**/**ICGC DCC**/**ICGC 25K**: original use case for Score from which the generic product has grown. The project portal is now retired: [dcc.icgc.org](https://dcc.icgc.org/) 
- **Kids First DRC**/**KF**: [Kids First Data Resource Center](https://portal.kidsfirstdrc.org/login)
- **collaboratory**/**collab**/**Cancer Collaboratory**: Cloud computing platform for cancer research applications hosted until 2023 by OICR: [cancercollaboratory.org](https://cancercollaboratory.org/)

## Proposed Changes
This issue is an epic used to track locations within this repo that make project specific references, and the issues created to track this work.

### Issues List
- [x] https://github.com/overture-stack/score/issues/420
- [x] https://github.com/overture-stack/score/issues/421
- [x] https://github.com/overture-stack/score/issues/422
- [x] https://github.com/overture-stack/score/issues/423
- [x] https://github.com/overture-stack/score/issues/424
- [x] https://github.com/overture-stack/score/issues/437
- [x] https://github.com/overture-stack/score/issues/438
- [x] https://github.com/overture-stack/score/issues/439
- [x] https://github.com/overture-stack/score/issues/441
- [x] https://github.com/overture-stack/score/issues/442
- [x] https://github.com/overture-stack/score/issues/443
- [x] https://github.com/overture-stack/score/issues/444
- [x] https://github.com/overture-stack/score/issues/446
- [x] https://github.com/overture-stack/score/issues/447
- [x] https://github.com/overture-stack/score/issues/449
- [x] https://github.com/overture-stack/score/issues/458
- [x] https://github.com/overture-stack/score/issues/459
- [x] https://github.com/overture-stack/score/issues/460
- [x] https://github.com/overture-stack/score/issues/461
- [x] https://github.com/overture-stack/score/issues/462
- [x] https://github.com/overture-stack/score/issues/463
- [x] https://github.com/overture-stack/score/issues/473
- [x] https://github.com/overture-stack/score/issues/474
- [x] https://github.com/overture-stack/score/issues/475

## Contributing
If there are legacy project references that you discover that are not yet tracked here please open a new issue with details of the where in the repository the reference is made. Please link those issues to this one so that we can track them together.

**Comment by joneubank** [comment]
Complete!
